name: Build and benchmark

on: [push]
jobs:
  build-and-bench-self-hosted:
    runs-on: self-hosted
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          clean: false

      - name: OpenCL Info
        run: clinfo

      - name: Update dependencies
        run: |
          git submodule update --init --recursive
          git submodule update --remote deps/graphblas-sharp/

      - name: Build Spla
        run: python3 scripts/build_spla.py

      - name: Build LAGraph
        run: python3 scripts/build_lagraph.py

      - name: Build GraphBLAST
        run: python3 scripts/build_graphblast.py
        
      - name: Build GraphBLAS-sharp
        run: bash scripts/build_graphblas-sharp.sh

      - name: Download matrices
        run: python3 scripts/download_matrices.py

      - name: BFS Benchmark. LAGraph, GraphBLAST, SPLA
        run: python3 scripts/benchmark.py --tool lagraph graphblast spla --algo bfs --platform 0

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
