name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: git submodule update --init --recursive
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' 
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      #- name: Build LAGraph
      #  run: python3 scripts/build_lagraph.py
      - name: Build GraphBLAS-sharp
        run: |
          cd deps/graphblas-sharp
          echo "1"
          chmod +x build.sh
          echo "2"
          ./build.sh DotnetBuild
          echo "3"
          cd ../../
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
